### ISSUE TITLE
Don't use FS

### ISSUE THREAD

**Issue by jods4** [jods4/aurelia-webpack-build#1]
From @niieani
> a potential problem: you are requiring the Node fs module, which is incorrect for any Webpack plugins or loaders. The reason is filesystems can be replaced/mocked by Webpack in certain conditions and make it dynamic or in-memory, and Webpack provides an interface to use the internal fs module, available to the loaders and plugins

**Comment by jods4** [comment]
Fixed, now both `ExtensionsDependenciesPlugin` and `GlobDependenciesPlugin` probe the `compilation.inputFileSystem` instead of `fs` directly.

**Comment by niieani** [comment]
Nice one. 👍
