### ISSUE TITLE
PreserveNameModule crash on scoped modules

### ISSUE THREAD

**Issue by jods4** [jods4/aurelia-webpack-build#12]
For example `@intogrey/aurelia-draggable`.
CC @Vheissu

**Comment by Vheissu** [comment]
I'll see if I can find out what's going in as well. Not sure how that resolution logic works. Theoretically it seems like the path is being normalized and part of that step is to strip put slashes.

**Comment by jods4** [comment]
I know what happens, it's no biggie to fix.

**Comment by jods4** [comment]
famous last words.

Anyway, scoped modules should work now. Please re-open this issue if it doesn't work for you.
