### ISSUE TITLE
aurelia-i18n doens't work

### ISSUE THREAD

**Issue by lares83** [jods4/aurelia-webpack-build#18]
I have an issue with adding aurelia-i18n to new webpack configuration:
I use webpack config from demo `04-Small_ES6_build`
In my main.ts I added

```
.plugin(PLATFORM.moduleName('aurelia-i18n'), (instance) => {
      // register backend plugin
      instance.i18next.use(Backend.with(aurelia.loader));
      return instance.setup({
        backend: {
          loadPath: './locales/{{lng}}/{{ns}}.json', // <-- XHR settings for where to get the files from
        },
        lng: 'pl',
        attributes: ['t', 'i18n'],
        fallbackLng: 'en',
        debug: false
      });
    });
```

and in console I receive this error
`Error: Unable to find module with ID: aurelia-i18n/t`

**Comment by ckotzbauer** [comment]
This has been fixed with https://github.com/aurelia/i18n/pull/202. But it's not released to npm yet. The only quick solution is to clone and build the i18n repo (the changes have to be in the dist folder) and install it with npm from your file system...

**Comment by jods4** [comment]
In the meantime, the other quick solution is to use 
```js
new ModuleDependenciesPlugin({
  "aurelia-i18n": ["./t", "./nf", "./df", "./rt"]
})
```

**Comment by lares83** [comment]
@jods4 it works thanks for your help :)
