### ISSUE TITLE
Fail to bundle vendor.css using aurelia plugin and extract-text-webpack-plugin

### ISSUE THREAD

**Issue by NunoCruzSW** [jods4/aurelia-webpack-build#19]
aurelia plugin and extract-text-webpack-plugin don't  well together

```
const path = require("path");
const { DllPlugin } = require("webpack");
const { AureliaPlugin } = require("aurelia-webpack-plugin");
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var extractCSS = new ExtractTextPlugin('vendor.css');

module.exports = {
  entry: {
    vendor: [
      "aurelia-bootstrapper",      
      "aurelia-router",
      "bootstrap/dist/css/bootstrap.css"
    ],
  },
  output: {
    path: path.resolve("dist"),
    filename: "[name].js",
    library: "[name]_[hash]",
  },
  resolve: {
    extensions: ['.js'],
  },
  module: {
      loaders: [
          { test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, loader: 'url-loader?limit=100000' },
          { test: /\.css(\?|$)/, 
              use: extractCSS.extract(['css-loader']),
          },
          { test: /bootstrap\/dist\/js\/umd\//, loader: 'imports?jQuery=jquery' }
      ]
  },
  plugins: [
    extractCSS,
    new DllPlugin({
      path: path.resolve("dist", "[name]-manifest.json"),
      name: "[name]_[hash]",
    }),
    new AureliaPlugin({
        aureliaApp: undefined
    })
  ],
};
```

this will make the build fail
```
ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module parse failed: C:\Users\nuno\aurelia-webpack-build\demos\05-DllReferencePlugin\node_modules\bootstrap\dist\css\bootstrap.css Unexpected token (7:5)
You may need an appropriate loader to handle this file type.
|  */
| /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
| html {
|   font-family: sans-serif;
|   -webkit-text-size-adjust: 100%;
 @ dll vendor
```

is looking like is missing an handler to css, but if we remove the aurelia plugin from the list it start to work

**Comment by jods4** [comment]
There is nothing specific about CSS in `AureliaPlugin`, so I don't see how that would be related.
Only thing that comes to mind: do you use `<require>` for your CSS (directly, or indirectly, e.g. in 3rd party libs)? Because that would obviously not work.

**Comment by NunoCruzSW** [comment]
no, to reproduce this I cloned this repo, move to demos\05-DllReferencePlugin, type npm install bootstrap and changed the vendor config as you see.  I just changed the webpack config, nothing else.

**Comment by jods4** [comment]
I fail to see how this can be related to `AureliaPlugin` then.
`bootstrap/dist/css/bootstrap.css` is in your entry point, webpack resolves it but fails to parse. Seems like a loader config issue.

**Comment by NunoCruzSW** [comment]
maybe isn't AureliaPlugin, but is strange because adding noHtmlLoader: true make the error stop'

**Comment by jods4** [comment]
`noHtmlLoader` avoids the plugin adding `html-resource-loader` for all `.html` files:
https://github.com/aurelia/webpack-plugin/blob/master/src/AureliaPlugin.ts#L163
In itself, this has no impact on CSS files, obviously. That loader just looks for stuff like `<require>` and adds more dependencies.

Wild guesses:
- One HTML file parsed by `html-resource-loader` adds more dependencies (e.g. from a `<require>` or `<compose>`), and those dependencies then trigger a bug.
- the `test: /\.html?$/` of `html-resource-loader` matches something it shouldn't, like `x.css?i.html`

**Comment by NunoCruzSW** [comment]
I gonna close this, it must be the extract-text-webpack-plugin doing something wrong

**Comment by jods4** [comment]
@NunoCruzSW I found out what your problem is.
Use `module.rules` rather than `module.loaders` (it's the same option, just another name).
The latter is not in the new documentation and is only supported for compatibility with webpack 1.x.

What happens is that without `noHtmlLoader`, `AureliaPlugin` adds the loader to `module.rules`, which is now defined so `module.loaders` is completely ignored.

I'm going to support both in the next release to prevent such problems to happen again.
