### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by nashwaan** [jods4/aurelia-webpack-build#20]
Hi jods4,

Thanks for this great work to simplify Aurelia + Webpack setup.

I tested this and it doesn't work on IE11.

The error in the console says `SCRIPT1014: Invalid character`.
It doesn't recognize ES6 string template, the ` character.
Is it because not transpiling from ES6 to ES5?

**Comment by MeirionHughes** [comment]
I imagine you'll need to add on the babel loader after the ts-loader.

**Comment by jods4** [comment]
In the interest of keeping those minimal, none include a `Promise` polyfill, which is a requirement to run Aurelia on IE.

Add NPM package `es6-promise-promise` and then: 
```js
plugins: [
  new AureliaPlugin(),
  new webpack.ProvidePlugin({
    Promise: "es6-promise-promise"
  })
]
```

The error you mention is a syntax error, so I assume you tried `04-Small_ES6_Build`, which as the name says is an ES6 output, which won't work in IE. 
All others are configured to transpile to ES5, so they should work in IE.

**Comment by nashwaan** [comment]
Yes, I was trying `04-Small_ES6_Build` thinking this demo was for transpiling **from** ES6 to ES5. Now i understand that this demo is meant to **produce** ES6 code.

**Comment by jods4** [comment]
Yes, it's actually the only one that does _not_ transpile to ES5. All others are using TypeScript with `es5` output.

**Comment by jods4** [comment]
I use it in my experiments to check how small the output can be made. ES6 code is smaller than ES5.
