### ISSUE TITLE
Wrong dependency in documentation

### ISSUE THREAD

**Issue by arnonuem** [jods4/aurelia-webpack-build#21]
On the wiki page the documentation says 'aurelia-webpack-loader@2.1.0'.
NPM is listing this module as 'aurelia-loader-webpack - v2.1.0'.

Please update the documentation from 'aurelia-webpack-loader@2.1.0' to 'aurelia-loader-webpack@2.1.0'

**Comment by jods4** [comment]
Good catch.
Actually I'm going to remove it, because you don't need the explicit dependency anymore. `aurelia-webpack-plugin` manages that for you now.
