### ISSUE TITLE
Can't run the 03-Code_splits example

### ISSUE THREAD

**Issue by Vaccano** [jods4/aurelia-webpack-build#27]
when I run `webpack` on the 03-Code_splits example I get the following error:

>const { AureliaPlugin } = require("aurelia-webpack-plugin");
...........^  (Dots added so that it will line up with the `{` symbol)

>SyntaxError: Unexpected token {

I went and updated the webpack.config.js file so that the line with the error reads: 

`const AureliaPlugin = require("aurelia-webpack-plugin");`

But then I get another error:

>C:\myPath\demos\03-Code_splits\node_modules\aurelia-webpack-plugin\dist\AureliaPlugin.js:16
    constructor(options = {}) {
.............................................^ (Dots added so that it will line up with the `=` sign)

>SyntaxError: Unexpected token =

**Comment by jods4** [comment]
You need Node 6+ to run this.
