### ISSUE TITLE
Need a demo for unit testing

### ISSUE THREAD

**Issue by nashwaan** [jods4/aurelia-webpack-build#31]
Hi @jods4,

Thank you for providing these excellent demos that clearly show what is minimally needed to achieve each objective.

Can you provide one more demo that shows how to setup unit testing using [StageComponent](http://aurelia.io/hub.html#/doc/article/aurelia/testing/latest/testing-components) (based on Jasmine)?

**Comment by jods4** [comment]
I don't think that I will. 
I want to keep these demos short and minimal. 

Testing has lots of possible choices like what framework do you use (e.g. Jasmine), what runner do you use (e.g. Karma); do you do Unit Testing, End-to-end, or...?

Maybe I'll do one basic testing demo one day, but otherwise I think you should wait for official @niieani's update skeleton, which includes everything including tests.

**Comment by niieani** [comment]
The skeleton with unit testing is ready: https://github.com/aurelia/skeleton-navigation/pull/714.

**Comment by nashwaan** [comment]
@niieani The new skeleton has two methods of doing unit testing: jest and karma. I was looking for an example of running karma (browser based) test using StageComponent.
The `welcome.test.js` file does this but it is for jest system.

Can you provide a similar example `welcome.spec.js` that is compiled by webpack and runs on the browser?

**Comment by niieani** [comment]
@nashwaan I will see what I can do, as soon as I have some time.

**Comment by nashwaan** [comment]
I am sure you can fix this @niieani. I believe @jods4 can provide invaluable help into getting `StageComponent` to work in webpack as he did a great job in the `aurelia-webpack-plugin`.

I feel that if the two of you can allocate some time together into this issue, then it will be fixed in no time!

By the way, looking at how the new skeleton emerged, it is nothing short of a **masterpiece**: versatile, concise, intuitive, modular, forward-thinking, and well architected.
👍👍👍👍👍

**Comment by nashwaan** [comment]
Thanks @niieani for solving this long pending issue. I see that you used this solution in the pretest:

```js
import {install as installJasmineAsync} from 'jest-jasmine2/jasmine-async';
installJasmineAsync(global); // enable running Promise-returning tests
```

Although I initially found it weird to borrow the functionality from `jest` to make it work in the browser, but it did the trick quite nicely.

Thanks a million for this!
😊😊😊😊😊😊
