### ISSUE TITLE
Code splitting only one route

### ISSUE THREAD

**Issue by dweber019** [jods4/aurelia-webpack-build#34]
@jods4 Is it true that I can't code split only a few specific routes?

Example from https://github.com/jods4/aurelia-webpack-build/blob/master/demos/03-Code_splits/src/app.ts#L11.

I can do:
```javascript
{ route: '', name: 'hello', moduleId: PLATFORM.moduleName('page-hello', 'hello') },
{ route: 'about', name: 'about', moduleId: PLATFORM.moduleName('page-about', 'about') },
```
All routes have a chunk name.

But I can't do:
```javascript
{ route: '', name: 'hello', moduleId: PLATFORM.moduleName('page-hello') },
{ route: 'about', name: 'about', moduleId: PLATFORM.moduleName('page-about', 'about') },
```
See the missing second parameter in `page-hello`.

My current behavior/issue?:
- If I have all route configs with a chunk name everything works as expected.
- If I have only a few specific route config entires with a chunk name, at least one missing, then Webpack compiles to only one file. No chunk files for routes.

**Comment by jods4** [comment]
This is not the behavior I'm seeing.

Using the 03 demo, modified like you suggest I'm getting this output:
```
   Asset       Size  Chunks                    Chunk Names
about.js  714 bytes       0  [emitted]         about
 main.js     795 kB       1  [emitted]  [big]  main
```

**Comment by dweber019** [comment]
Hmmm... probably an issue with the new skeleton-typescript-webpack.
When I have this config:
```javascript
{ route: ['', 'welcome'], name: 'welcome',      moduleId: PLATFORM.moduleName('./welcome', 'weclome'),      nav: true, title: 'Welcome' },
{ route: 'users',         name: 'users',        moduleId: PLATFORM.moduleName('./users', 'users'),        nav: true, title: 'Github Users' },
{ route: 'child-router',  name: 'child-router', moduleId: PLATFORM.moduleName('./child-router'), nav: true, title: 'Child Router' },
```
I get this output in Webpack:
```bash
fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]
f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]
  e18bbf611f2a2e43afc071aa2f4e1512.ttf    45.4 kB          [emitted]
  674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
  912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]
  b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]
af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
  89889688147bd7575d6327160d64e760.svg     109 kB          [emitted]
 fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
       0.42790961c3f09974199e.chunk.js    13.7 kB       0  [emitted]
    app.42790961c3f09974199e.bundle.js    1.57 MB       1  [emitted]  [big]  app
 vendor.42790961c3f09974199e.bundle.js     873 kB       2  [emitted]  [big]  vendor
     0.42790961c3f09974199e.bundle.map    16.2 kB       0  [emitted]
   app.42790961c3f09974199e.bundle.map    1.76 MB       1  [emitted]         app
vendor.42790961c3f09974199e.bundle.map    1.04 MB       2  [emitted]         vendor
                            index.html  730 bytes          [emitted]
```
As you can see no `welcome` and `user` chunk file.

Also when I do a check in a browser there are no addition chunks loaded when switching to the users route.

**Comment by jods4** [comment]
You should use Webpack to find out where your modules are and what is depending upon them.

From the output I can guess you have a complicated config. Note that creating a dependency to a new chunk does not guarantee in itself that you'll have a separate file in the end:
- From the output I guess your using `CommonsChunkPlugin`, which is explicitly moving modules around in other chunks (if they are found in more than one). Several other plugins do so (based on size, number of modules, etc);
- If another module in the main chunk depends on the module you wanted to put in another chunk, Webpack will be intelligent enough to pull it back in the main chunk;
- It's also possible to put several chunks in the same file;
- BTW: what's your `0` chunk? The name of the file doesn't have to match the name of the chunk, depending on your config.

**Comment by dweber019** [comment]
Ok will do a deep dive into the skeleton-navigation regarding this issue. It would be nice if the official skeleton of Aurelia would support this out of the box, so I'll have a look.

My webpack config ca be viewed here https://github.com/dweber019/skeleton-navigation-lazy-routes. It's a fork of the offical skeleton-navigation from Aurelia, based on the latest master with a little fix I made an contibuted as PR.

**Comment by jods4** [comment]
Just to be sure: did you notice the child router?

**Comment by dweber019** [comment]
I got it.

It's fully working.

The `child-router` has a router config too and in this config there are references to the `users` and `welcome` module. So as long as the `child-router` isn't chunked, no other module used in the `child-router` router config is chunked too.

Makes sense ;)
