### ISSUE TITLE
Building an Aurelia plugin w/ webpack

### ISSUE THREAD

**Issue by michaelbull** [jods4/aurelia-webpack-build#37]
Hi, I'm trying to build an Aurelia plugin with webpack as the build system.

Looking at the plugin skeletons from other projects, they only export their [built src](https://github.com/SpoonX/aurelia-plugin-skeleton/blob/master/dist/native-modules/aurelia-plugin-skeleton.js) and not the entirety of Aurelia. All of the webpack build examples I've seen use `entry: 'aurelia-bootstrapper'`, which means that the built distribution includes everything like aurelia-templating, aurelia-binding, etc.

Can you provide some assistance as to how we build a distribution of the relevant src files to be consumed as an Aurelia plugin? Thanks in advance.

**Comment by jods4** [comment]
That's a very good question!

My advice is to distribute your library in source format, i.e. do not try to bundle it. Bundling will happen when users build their app.
If you need to compile files (e.g. you write Typescript code, or use Babel with ES6+), just do that into a dist folder. Make it a 1-to-1 compilation.

It's unrelated but look at the `aurelia-webpack-plugin` project for an example of TS compilation, while keeping everything in its own file.

Aurelia is dependent on specific modules structure. Whatever you do, Aurelia resources _have to_ stay in their own file (e.g. if you create a custom element).

If you still want to package your sources (when they can, not the resources!), rollup is probably a better choice.

**Comment by michaelbull** [comment]
Hi @jods4. Thanks for the reply.

Looking at libraries such as [`aurelia-validation`](https://github.com/aurelia/validation), they produce distributions of the source code to support bundling across multiple module types (amd/commonjs/es2015/es2017 etc...). I was wondering if there's a simple way to produce all of these distributions using webpack to avoid the [ridiculous amount of npm scripts](https://github.com/aurelia/validation/blob/master/package.json#L28) that others are using.

Does this functionality exist? Or would it be necessary to extend the `aurelia-webpack-plugin` to add such behaviour?

**Comment by jods4** [comment]
`aurelia-webpack-plugin` doesn't care about that because it only targets modern Node runtimes.

It depends what source you use to build your project.
I will assume that you use Typescript.

Then if you look carefully, what `aurelia-webpack-plugin` does is compile `src` with `tsc` and it's configured to output the results in `dist/`.

If you want multiple distributions you can call `tsc` multiple times, with slightly different configs (pass the config file with `--project`).
The variations are easy to do thanks to `extends` property that enables `tsconfig.json` inheritance.

What you'll need for each build is the correct combination of `target`, `module` and `outdir`.

**Comment by jods4** [comment]
@michaelbull is there anything actionable that I could do related to this issue, or can I close it?

**Comment by michaelbull** [comment]
Hi @jods4, the only thing I think we could look to resolve is the necessity for all of [this package.json spam](https://github.com/aurelia/validation/blob/master/package.json#L27) to produce the different distributions. I think a webpack plugin could achieve this but I'm not sure - keen to hear your opinion and would be wiling to work on it with you.

**Comment by jods4** [comment]
My own personal repo for small webpack examples is probably not the right place for this discussion, so I'll go ahead and close the issue. Feel free to open a new issue in a repo like `aurelia/framework`, `aurelia/cli`, `aurelia/skeleton-*` -- whatever seems more appropriate for basic setup discussion.

My 2¢ on the package you've linked: if you're trying to do it all with shell / package.json, it doesn't actually contain much. 
It contains **6** different distributions and each one comes with **three simple steps**:
- cleaning the destination;
- building ts;
- adding some extra resources such as html and css to the destination.

Yes that's 18 lines and personally I don't quite like the look of that file.
I would probably try to generalize the build of one distribution in a single function and then be able to invoke it from an array of distributions...
Looks like I'm headed to a build system? Coders are really running in circles, aren't we? 😉
