### ISSUE TITLE
Removing webpack-dependency-suite

### ISSUE THREAD

**Issue by jods4** [jods4/aurelia-webpack-build#6]
@niieani
Currently my demos and webpack Aurelia plugins still use one last piece of `webpack-dependency-suite`: the `list-based-loader`. I need it so that framework dynamic dependencies are properly included (based on `aurelia.build.resources` in `package.json`).

My understanding is that it was decided to also/instead insert `PLATFORM.moduleName()` anywhere in framework code, where a dynamic dependency is.

Can you please let me know when this is done? Once it is, I'll be able to remove `list-based-loader`, which doesn't integrate nicely with the rest of my plugins.

**Comment by niieani** [comment]
Feel free to send PRs to all the places in Aurelia where that's required in our code. Just post the links to the PRs here and I'll review them ASAP. I've been pretty busy with some other stuff recently, hence my unavailability in the last few days.

Thanks!

**Comment by jods4** [comment]
We can freely do PR in all aurelia libs to add a `PLATFORM.moduleName()` anywhere there's a dynamically loaded module?
I assumed that since `PLATFORM` won't be removed when not running the webpack plugin, a real implementation has to be properly imported, right -- as opposed to being a global placeholder?

**Comment by niieani** [comment]
Yes. The real implementation is there in `aurelia-pal`, in fact it's been recently released. It simply returns the value of the first parameter. Ultimately we'll want all the build steps to remove the redundant calls (pretty simple to do with a babel plugin), but for now we can just leave it as is, Rob agreed that the trade-off of the extra function call in a non-Webpack environment during the transitional phase is acceptable.
